name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: dropdown
    id: integration
    attributes:
      label: Integration
      description: Which integration is this for?
      options:
        - Vanilla JavaScript library
        - React component
        - Vue component
        - Angular component
        - Svelte component
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the feature or improvement you'd like to see.
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Use case
      description: Why do you need this feature? What problem does it solve?
    validations:
      required: true
