// Runs the appropriate npm script when matching source files change.
import chokidar from "chokidar";
import { spawn } from "node:child_process";

// Chokidar v4+ no longer supports globs, so we watch directories and filter events via the `ignored` callback. The callback receives absolute paths and (when available) a fs.Stats object — we must allow directories to be traversed.
const watchers = [
  {
    name: "js",
    paths: ["packages/core/src/js"],
    ignored: [
      /\/packages\/core\/src\/js\/i18n(\/|$)/, // handled by translations watcher
      /\/packages\/core\/src\/js\/utils\.js$/, // handled by utils watcher
    ],
    script: "build:jsfast",
  },
  {
    name: "utils",
    paths: ["packages/core/src/js/utils.js"],
    scripts: ["build:utils", "build:jsfast"],
  },
  {
    name: "translations",
    paths: ["packages/core/src/js/i18n"],
    // index.ts is regenerated by build:translations itself — ignoring it here prevents an infinite watch → build → watch loop.
    ignored: /\/packages\/core\/src\/js\/i18n\/index\.ts$/,
    script: "build:translations",
  },
  {
    name: "react",
    paths: [
      "packages/react/src",
      "packages/react/demo",
    ],
    ignored: /-bundle\.js$/, // generated bundles
    script: "build:react",
  },
  {
    name: "vue",
    paths: ["packages/vue/src"],
    script: "build:vue",
  },
  {
    name: "angular",
    paths: [
      "packages/angular/src",
      "packages/angular/demo",
    ],
    ignored: /-bundle\.js$/, // generated bundles
    script: "build:angular",
  },
  {
    name: "css",
    paths: ["packages/core/src/css"],
    ignored: /\/packages\/core\/src\/css\/flag-offsets\.css$/, // generated by build:img
    script: "build:css",
  },
];

// Per-watcher debounce + serialization so a burst of saves only triggers one rebuild.
const state = new Map();
function trigger(w) {
  const s = state.get(w.name);
  clearTimeout(s.debounce);
  s.debounce = setTimeout(() => {
    if (s.running) {
      s.queued = true;
      return;
    }
    runOnce(w);
  }, 100);
}
async function runOnce(w) {
  const s = state.get(w.name);
  s.running = true;
  s.queued = false;
  const scripts = w.scripts ?? [w.script];
  for (const script of scripts) {
    console.log(`\n[watch:${w.name}] -> npm run ${script}`);
    const code = await new Promise((resolve) => {
      const child = spawn("npm", ["run", script], { stdio: "inherit" });
      child.on("exit", (c) => resolve(c ?? 1));
    });
    if (code !== 0) {
      console.log(`[watch:${w.name}] FAILED (exit ${code})`);
      break;
    }
  }
  s.running = false;
  if (s.queued) runOnce(w);
}

for (const w of watchers) {
  state.set(w.name, {
    running: false,
    queued: false,
    debounce: null,
  });
  chokidar
    .watch(w.paths, { ignoreInitial: true, ignored: w.ignored })
    .on("all", () => trigger(w));
  console.log(`[watch:${w.name}] watching ${w.paths.length} pattern(s)`);
}
