// Replacement for grunt-contrib-watch — runs the appropriate npm script when matching source files change. Mirrors grunt/watch.js one-for-one.
import chokidar from "chokidar";
import { spawn } from "node:child_process";

// Chokidar v4+ no longer supports globs, so we watch directories and filter events via the `ignored` callback. The callback receives absolute paths and (when available) a fs.Stats object — we must allow directories to be traversed.
const watchers = [
  {
    name: "js",
    paths: ["src/js"],
    ignored: (p, stats) => {
      if (!stats) return false;
      if (stats.isDirectory()) return p.endsWith("/src/js/i18n");
      if (p.includes("/src/js/i18n/")) return true; // handled by translations watcher
      if (p.endsWith("/src/js/utils.js")) return true; // handled by utils watcher
      return !p.endsWith(".ts");
    },
    script: "build:jsfast",
  },
  {
    name: "utils",
    paths: ["src/js/utils.js"],
    scripts: ["build:utils", "build:jsfast"],
  },
  {
    name: "translations",
    paths: ["src/js/i18n"],
    // index.ts is regenerated by build:translations itself — ignoring it here prevents an infinite watch → build → watch loop.
    ignored: (p, stats) => {
      if (!stats || stats.isDirectory()) return false;
      if (p.endsWith("/src/js/i18n/index.ts")) return true;
      return !p.endsWith(".ts");
    },
    script: "build:translations",
  },
  {
    name: "react",
    paths: [
      "react/src/IntlTelInput.tsx",
      "react/demo/set-number/SetNumberApp.tsx",
      "react/demo/simple/SimpleApp.tsx",
      "react/demo/toggle-disabled/ToggleDisabledApp.tsx",
      "react/demo/validation/ValidationApp.tsx",
    ],
    script: "build:react",
  },
  {
    name: "vue",
    paths: ["vue/src/IntlTelInput.vue"],
    script: "build:vue",
  },
  {
    name: "angular",
    paths: [
      "angular/src/IntlTelInput.ts",
      "angular/demo/form/form.component.ts",
      "angular/demo/set-number/set-number.component.ts",
      "angular/demo/simple/simple.component.ts",
      "angular/demo/toggle-disabled/toggle-disabled.component.ts",
      "angular/demo/validation/validation.component.ts",
    ],
    script: "build:angular",
  },
  {
    name: "css",
    paths: ["src/css"],
    script: "build:css",
  },
];

// Per-watcher debounce + serialization so a burst of saves only triggers one rebuild.
const state = new Map();
function trigger(w) {
  const s = state.get(w.name);
  clearTimeout(s.debounce);
  s.debounce = setTimeout(() => {
    if (s.running) {
      s.queued = true;
      return;
    }
    runOnce(w);
  }, 100);
}
async function runOnce(w) {
  const s = state.get(w.name);
  s.running = true;
  s.queued = false;
  const scripts = w.scripts ?? [w.script];
  for (const script of scripts) {
    console.log(`\n[watch:${w.name}] -> npm run ${script}`);
    const code = await new Promise((resolve) => {
      const child = spawn("npm", ["run", script], { stdio: "inherit" });
      child.on("exit", (c) => resolve(c ?? 1));
    });
    if (code !== 0) {
      console.log(`[watch:${w.name}] FAILED (exit ${code})`);
      break;
    }
  }
  s.running = false;
  if (s.queued) runOnce(w);
}

for (const w of watchers) {
  state.set(w.name, {
    running: false,
    queued: false,
    debounce: null,
  });
  chokidar
    .watch(w.paths, { ignoreInitial: true, ignored: w.ignored })
    .on("all", () => trigger(w));
  console.log(`[watch:${w.name}] watching ${w.paths.length} pattern(s)`);
}
